### ISSUE TITLE
Deployment on production

### ISSUE THREAD

**Issue by Steinsplitter** [toollabs/upload-stats-bot#2]
fe29ce9748f0ebc6ce10a9c98015af68a2fd716b need to be deployed on production (git pull).

steinsplitter@tools-sgebastion-07:~$ become upload-stats-bot
You are not a member of the group tools.upload-stats-bot.
Any existing member of the tool's group can add you to that.

and no automatic deployment:
steinsplitter@tools-sgebastion-07:/data/project/upload-stats-bot$ sed -n 42p update.js
        version: '0.0.0.3',

**Comment by Rillke** [comment]
Sorry about that. Going to deploy in an hour or so and grant you access.

**Comment by Rillke** [comment]
@Steinsplitter You now have permissions and your changes are deployed. Thanks for opening this issue. BTW, I have the feeling that the upload count is not updated. Did you check all the SQL queries?

**Comment by Steinsplitter** [comment]
Query is working, seems to be a problem with saving the pages, likely because stuff in the api has been changed as well. But have to give a deep look.

debug:   API action: edit
debug:   48/48: POST <https://commons.wikimedia.org:443/w/api.php>
debug:   POST fields: action, title, text, bot, summary, token, assert, format

**Comment by Steinsplitter** [comment]
Was able to fine the issue, it is the timeout. The actor views are terribly slow.

So i changed the timeout in fc6f1e11f366c5fead1a928948033d05e45fc102 , but it is slow and query's are running forever.

**Comment by Rillke** [comment]
> Maybe the database team at toolsforge if fixing the issue with slow joins to the actor table.

Is there a Phabricator Task asking for faster actor view joins?

**Comment by Steinsplitter** [comment]
Talked to the DBA, 2f58f324f8ed1f05958d84de9f68f287a2bed8a8 should make it faster. I did a test, and i can confirm:

> MariaDB [commonswiki_p]> SELECT count(*) AS count FROM image INNER JOIN actor_image ON img_actor = actor_id WHERE actor_name="Steinsplitter" ORDER BY img_timestamp DESC;
> +-------+
> | count |
> +-------+
> |  2719 |
> +-------+
> 1 row in set (0.08 sec)
> 
> 
> MariaDB [commonswiki_p]> SELECT count(*) AS count FROM image INNER JOIN actor ON img_actor = actor_id WHERE actor_name="Steinsplitter" ORDER BY img_timestamp DESC;
> +-------+
> | count |
> +-------+
> |  2719 |
> +-------+
> 1 row in set (0.59 sec)
